name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare third-party dependencies
      run: ./thirdparty.sh

    - name: Build and test
      run: ./build_all.sh
